version: '3'
services:
  nest-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: nest-server-image
    container_name: nest-server-image-ctn
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - node-network
    command: npm run start:dev

  mongodb:
    image: mongo:4.2.1-bionic
    container_name: mongo-ctn
    volumes:
      - ./dbdata:/data/db
    networks:
      - node-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
